# Generated by Django 4.1.2 on 2022-10-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_users_password_users_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
