# Generated by Django 4.1.2 on 2022-10-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_users_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(help_text='Введите ник пользователя', max_length=20, unique=True),
        ),
    ]
