# Generated by Django 4.1.2 on 2022-10-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
